#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y install percona-xtrabackup
apt-get -y install percona-xtradb-cluster-server-5.5=5.5.37-25.10+dfsg-0ubuntu0.14.04.1 
apt-get -y install percona-xtradb-cluster-server 

# Don't auto start mysql (we'll start it up in guest)
update-rc.d mysql defaults
update-rc.d mysql disable
